[workspace]
authors = ["Hammad-hab <hammadalibutt30@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoINI"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025070705,<26"
