

context:
  version: "0.1.0"

package:
  name: "mojo-ini"
  version: ${{ version }}

source:
  - git: https://github.com/Hammad-hab/MojoINI.git
    rev: 32ff979d86393cf91068ead70e96ce18cd701106

build:
  number: 0
  script:
    - mojo package src/mojoini -o ${{ PREFIX }}/lib/mojo/mojoini.mojopkg
requirements:
  host:
    - max
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test test_parser.mojo
    files:
      recipe:
        - test.mojo

about:
  homepage: https://github.com/Hammad-hab/MojoINI.git
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  summary: Simple INI file parser for Mojo
  repository: https://github.com/Hammad-hab/MojoINI.git

extra:
  maintainers:
    - Hammad-hab
